import "@/styles/globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { TRPCReactProvider } from "@/trpc/react";
import React from "react";
import Navbar from "@/components/navbar";
import { Coda } from "next/font/google";

const coda = Coda({
  weight: ["400", "800"],
});

export const metadata = {
  title: "Chirag Aggarwal",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={coda.className}>
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className={`flex h-[100vh] flex-col p-2`}>
              <Navbar />
              {children}
            </main>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
